// THIS FILE IS GENERATED BY THE TOOL, PLEASE DON'T EDIT

using System;
using System.Collections;
using SimpleJSON;

namespace Config
{left}
	public class ConfigItem
	{left}
		public int Id;

		public virtual void Init(JSONNode node)
		{left}
			Id = node[0].AsInt;
		{right}	
	{right}	

{config_items}

{right}	
